FROM node:20-alpine AS builder

WORKDIR /app/client

COPY package*.json ./
RUN npm install -g @angular/cli
RUN npm install

COPY . .

EXPOSE 4200

ENV NODE_ENV=development

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
