FROM node:20-alpine AS build

WORKDIR /app/client

ENV NODE_ENV=production

COPY package.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

RUN npm install -g http-server

WORKDIR /app/client

COPY --from=build /app/client/dist/client .

EXPOSE 4200

CMD ["http-server", "-p", "4200"]