FROM node:20-alpine AS build

WORKDIR /app/client

ENV NODE_ENV=production

COPY package.json ./
RUN npm install
RUN npm install -g @angular/cli

COPY . .

RUN npm run build

FROM node:20-alpine AS base

RUN npm install -g angular-http-server

WORKDIR /app/client

COPY --from=build /app/client/dist/client .

EXPOSE 4200

CMD ["angular-http-server", "-p", "4200"]