version: '3.8'

services:
  db:
    container_name: database
    image: postgres:17-alpine
    env_file: ./environment/.env.database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - server-db

  server:
    container_name: server_dev
    env_file:
      - ./environment/.env.server
      - ./environment/.env.database
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app/server
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - server-db
      - client-server

  client:
    container_name: client_dev
    env_file: ./environment/.env.client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app/client
      - client_node_modules:/app/client/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - server
    networks:
      - client-server

networks:
  client-server:
    driver: bridge
  server-db:
    driver: bridge

volumes:
  db_data:
  client_node_modules:
