version: '3.8'

services:
  db:
    image: postgres:17-alpine
    env_file: ./environment/.env.database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - server-db

networks:
  client-server:
    driver: bridge
  server-db:
    driver: bridge

volumes:
  db_data:
