version: '3.8'
name: lib-frameworks-dev

services:
  db:
    container_name: database_dev

  server:
    container_name: server_dev
    env_file:
      - ./environment/.env.database
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app/server
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - server-db
      - client-server

  client:
    container_name: client_dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - server
    networks:
      - client-server
