version: '3.8'

services:
  server:
    container_name: server_dev
    env_file: ./environment/.env.server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - "8080:8080"

  client:
    container_name: client_dev
    env_file: ./environment/.env.client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - server