FROM node:20-alpine AS build

WORKDIR /app/server

COPY package.json package-lock.json ./
RUN npm install 

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app/server

COPY --from=build /app/server/dist ./dist
COPY --from=build /app/server/.env ./.env
COPY --from=build /app/server/node_modules ./node_modules
COPY --from=build /app/server/package.json ./package.json

ENV NODE_ENV=production

EXPOSE 8080

CMD ["node", "dist/src/main.js"]
